version: "3"

services:
    web:
      image: gwhsu/flask_service

      deploy:
        replicas: 1
        resources:
          limits:
            cpus: '0.2'
        placement:
          constraints:
            - "node.role==worker"
      ports:
        - "5000:5000"
